Repository pressbooks/buckram, pull requests merged in 2018-10, with the labels that each got.

#231 Add font-weight: normal to paragraph styles (fix #222)
  assets/styles/components/elements/_paragraphs.scss
Labels: enhancement

#230 Omit link colour rules for EPUB/MOBI (fix #226)
  assets/styles/components/_colors.scss
  assets/styles/components/toc/_generic.scss
  assets/styles/variables/_colors.scss
Labels: a11y, enhancement

#232 Fix decoration colours
  assets/styles/components/pages/_titles.scss
  assets/styles/components/section-titles/_back-matter.scss
  assets/styles/components/section-titles/_chapters.scss
  assets/styles/components/section-titles/_front-matter.scss
  assets/styles/components/section-titles/_parts.scss
  assets/styles/variables/_colors.scss
Labels: enhancement

#233 Fix list variables which require if-map-get
  assets/styles/components/elements/_lists.scss
  assets/styles/variables/_elements.scss
Labels: enhancement

#237 Add CC0 icons (fix #236)
  assets/images/cc-zero.png
  assets/images/cc-zero.svg
  assets/images/public-domain.png
Labels: enhancement

#244 Add extra margins for publisher and publisher city
  assets/styles/components/pages/_titles.scss
  assets/styles/variables/_pages.scss
Labels: enhancement

#242 Add top margin to dedication and epigraph
  assets/styles/components/pages/_front-matter.scss
  assets/styles/variables/_pages.scss
Labels: enhancement

#243 Add letter spacing and word spacing support for elements h1 through h6
  assets/styles/components/elements/_headings.scss
  assets/styles/variables/_elements.scss
Labels: enhancement

#247 Add border top styles and padding top for hr break symbols
  assets/styles/components/specials/_separators.scss
  assets/styles/variables/_specials.scss
Labels: enhancement

#245 Add variable for section license margin bottom
  assets/styles/components/pages/_front-matter.scss
  assets/styles/variables/_pages.scss
Labels: enhancement

#246 Add text align to footnote
  assets/styles/components/specials/_footnotes.scss
  assets/styles/variables/_specials.scss
Labels: help wanted

#252 Table line color
  assets/styles/components/elements/_tables.scss
  assets/styles/variables/_elements.scss
Labels: enhancement

#253 Fix alignment and word wrapping issues on tables (fix #227)
  assets/styles/components/elements/_tables.scss
  assets/styles/variables/_elements.scss
Labels: enhancement

#249 Add copyright margins (top, left, right)
  assets/styles/components/pages/_front-matter.scss
  assets/styles/variables/_pages.scss
Labels: enhancement
